# Generated by Django 2.2.11 on 2020-03-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.TextField()),
                ('year', models.IntegerField()),
                ('college', models.TextField()),
                ('interests', models.TextField()),
                ('skills', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
    ]
